[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5.30", features = ["derive"] }
anyhow = "1.0.95"
regex = "1.11.1"
